server:
  port: 8081

spring:
  application:
    name: account-service

logging:
  level:
    org.springframework.security: TRACE

#security:
#  user:
#    name: root
#    password: password
#  oauth2:
#    resource:
#      loadBalanced: true
#      userInfoUri: http://localhost:9999/user
security:
  sessions: stateless
  user:
    password: none
#token 公钥
  oauth2:
    resource:
      jwt:
        key-value: 123


eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
