spring:
  application:
    name: api-gateway


server:
  port: 8080


zuul:
  ignored-services: '*'
  prefix: /api
  routes:
   account-service: /account/**


eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

