server:
  port: 8080
#  context-path: /app

spring:
  application:
    name: api-gateway


logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE


zuul:
  ignored-services: '*'
#  prefix: /api
  routes:
   auth-server: /uaa/**
   account-service: /account/**
  sensitive-headers:

security:
 user:
   password: none
 oauth2:
  client:
    access-token-uri: http://localhost:8080/uaa/oauth/token
    user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
    client-id: testc

  resource:
   jwt:
     key-value: 123


eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

