server:
  port: 8080

spring:
  application:
    name: api-gateway


logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE


zuul:
  ignored-services: '*'
#  prefix: /api
  routes:
   auth-server: /uaa/**
   account-service: /account/**
  sensitive-headers:


eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

